import { BUDGET_COLOURS, budAct, budget, budgetBarHTML, budgetState, budgetSummaryHTML, catColour, catProjection, catSegStyle, commitBudget, committedThisWeek, dayBudget, fundableGoals, hrs, loadBar, loadState, logContribution, paintBudget, viewBudget } from './budget.js';
import { CAL } from './cal.js';
import { captureHint, doCapture } from './capture.js';
import { CK, CKROW, CK_MAX, ckAct, ckBack, ckNext, ckSaveProgress, findStep, setCK, startCheckin, subjHead, suggestDay, suggestTime } from './checkin.js';
import { renderCheckin } from './checkin.jsx';
import { CAL_E, CAL_S, CARDSUBS, calMinAt, calPos, dayStripHTML, itemCard } from './components/card.js';
import { ARMED, armConfirm, armLabel, disarm, newInAct, newInHTML, openConfirm, repaintArmed } from './components/dialogs.js';
import { swallowClick, wireDrag } from './components/drag.js';
import { FOCUSABLE, RETURN_FOCUS, closeModal, openModal } from './components/modal.jsx';
import { FIXABLE, TIL_EDIT, TIL_REVEAL, setTilEdit, setTilReveal, sigFixAct, sigResolverHTML } from './components/resolver.js';
import { SIGALL, SIGFIX, SIGOPEN, SIG_KIND, SIG_MAX, setSigAll, setSigFix, setSigOpen } from './components/ribbon.js';
import { renderSignals } from './components/ribbon.jsx';
import { DOWS, HUSH_AT, MONEY_TARGET, MONTHS, RULES, activeItems, addSub, applyFootprint, autoNextTitle, avgDelta, buildGoalFrom, cadenceOf, carryFootprint, carrySubs, checkinAgenda, checkinDue, classify, clearGate, completeStep, daysQuiet, driftPhrase, firstStepFor, floatSub, followThrough, hushed, itemsOn, lastDowKey, learnType, learnedScore, money, moveItem, openGates, overdueItems, overlap, parseClock, parseMoney, parseWhen, quietLimit, shortName, sigKey, sigLabel, signals, snoozeSignals, sortSubs, streak, subProgress, subs, termsOf, togglePrereq, toggleSub, unblockThread, unscheduledItems } from './engine.js';
import { DRIFT_CADENCE_TYPES, GOAL_GATE_FIELDS, LEARN_AFTER, TEMPLATES, TMPL_FIELDS, TMPL_GATE, acceptTmplGate, actualMins, applyTemplate, blankFootprint, catByName, catNameOf, clearActual, clearTmplGate, committedWeek, costTotal, declineTmplGate, duePrereqs, ensureFootprint, footLag, footLead, footWidth, fp, fpMeta, hasFootprint, matchTemplate, median, normCost, normFootprint, normPrereq, prereqById, prereqDueKey, proposeFromDrift, proposeFromDuration, queueTmplGate, recordSample, slotDur, startActual, stepCost, stepOfEvent, stopActual, timing, tmplAdd, tmplBuiltin, tmplEdited, tmplGates, tmplGet, tmplHide, tmplList, tmplReset, tmplSet, tmplShow } from './footprint.js';
import { GEROW, footRowHTML, geAct, goalEditorHTML, openConvert, openDefineNext, openEvent, openGoal, openPrefs, ordControls, parseCostSpec, parsePrereqSpec, refreshGoal, saveGoalFields, schedRowHTML, setGerow, subListHTML, tmplPrefsHTML, toggleStep, uiAct } from './goal-editor.js';
import { GDONE, GERR, GIS, GSTATE, GTIMER, GTOK, G_BACK_DAYS, G_FWD_DAYS, G_MAXPAGES, G_SCOPE, G_SYNCKEY, gAct, gAdopt, gApply, gCal, gCancel, gChips, gClientId, gConnect, gCursor, gCursorSet, gDead, gDisconnect, gDrop, gEnqueue, gFlush, gForeign, gFromRow, gISO, gLease, gLoadGIS, gMerge, gOn, gOriginOK, gPending, gPrefsHTML, gReadPrefs, gReadTime, gRequestToken, gStart, gStop, gSync, gToRow, gToken, gWinFrom, gWinTo, gapi, gmeta, gqueue, inWindow, setGErr } from './google.js';
import { EASE_MIN, EASE_START, EASE_STEP, FIRST_INTERVAL, HINT_UNTIL, TIL_RE, TIPS, TIP_DAYS, addNote, blankSrs, cardHTML, cardLabel, deleteNote, dueNotes, isCard, isTilCapture, newNote, noteById, parseCard, pendingTips, retireTip, reviewNote, stripTil, tilQueue, tipsOff, toggleHide, updateNote, wantsSyntaxHint } from './notes.js';
import { NOTIF_HARD_H, NOTIF_KEEP_DAYS, NOTIF_LEAD_MIN, NOTIF_TICK_MS, NOTIF_TIMER, NOTIF_WINDOW_MIN, installPrefsHTML, notifAlreadySent, notifDisable, notifEnable, notifMark, notifOn, notifPerm, notifPlan, notifPrefsHTML, notifSentList, notifShow, notifStart, notifStop, notifSupported, notifTick, notifTrackHard, notifWanted, plyGoTo } from './notify.js';
import { BUILD, INSTALL_EVT, SWREG, SWSTATE, SW_URL, SW_WHY, doInstall, installHint, iosWeb, registerSW, renderInstallBar, setInstallEvt, setSWREG, setSWSTATE, standalone, swBlockedBecause } from './pwa.js';
import { ANCHOR_SOURCES, CHURN_AT, CHURN_SOURCES, DRIFT_MIN_DAYS, DRIFT_SD_FACTOR, blankReschedule, bumpReschedule, churnAt, driftStats, noteReschedule, recomputeAllReschedule, rescheduleDrift, rescheduleHistory, rescheduleLifetime, rescheduleLine, rescheduleSummaryFromLog } from './reschedule.js';
import { SCHEMA } from './schema.js';
import { seed } from './seed.js';
import { DB, EPOCH, EXTERNAL, KEY, LEGACY_KEY, MEMONLY, PASS, PENDING, REDO, SHADOW, STAMP_SKIP, UNDO, addEvent, addGoal, adoptExternal, blankDB, checkpoint, commitCheckpoint, currentStep, deleteGoal, doneGoals, eachRec, eventById, eventsOn, exportJSON, findThread, finishGoal, goalById, goals, importJSON, lastDoneStep, liveGoals, load, logIt, masterEvent, migrate, newEvent, newGoal, newStep, newSub, newThread, occurrenceOf, occursOn, paintUndo, recSig, redo, removeEvent, reopenGoal, restoreSnapshot, save, setDB, shadowReset, skipOccurrence, stampOf, stepById, threadById, touchThread, undo } from './store.js';
import { PIPELINE_STAGES, TYPE } from './types.js';
import { addDays, clamp, daysBetween, dkey, el, esc, fmtDate, fmtDateY, fmtDay, fmtFull, fmtTime, nowMin, parseKey, relDays, startOfWeek, toast, today, uid } from './util.js';
import { goalState, listHidden } from './views/list.jsx';
import { bestQuadrant, doneCount, partialCount } from './views/quarter.js';
import { quarterRange } from './views/quarter.jsx';
import { QUAD, ZOOMS, captureView, lastZoomIdx, render, renderBody, restoreView, wireView } from './views/render.jsx';

/* ---------------------------------------------------------------------------
   The test seam.

   The monolith kept every function in one script scope, so a suite could reach
   anything. Modules close that door, so the door is reopened deliberately and in
   one place: the same surface the jsdom bridge exposes for the monolith, which is
   what lets one suite run against both targets and prove they behave alike.

   Reassigned bindings are getters — undo(), import and the demo seed REPLACE the
   database rather than mutating it, so a snapshot taken at boot would go stale.

   Generated to match test/bridge.js; see scripts/gen-debug.mjs.
--------------------------------------------------------------------------- */
export const API = {
  esc,
  el,
  uid,
  clamp,
  dkey,
  parseKey,
  today,
  addDays,
  daysBetween,
  startOfWeek,
  fmtDay,
  fmtDate,
  fmtFull,
  fmtDateY,
  fmtTime,
  nowMin,
  relDays,
  toast,
  money,
  hrs,
  SCHEMA,
  KEY,
  LEGACY_KEY,
  blankDB,
  migrate,
  load,
  save,
  exportJSON,
  importJSON,
  checkpoint,
  commitCheckpoint,
  restoreSnapshot,
  adoptExternal,
  undo,
  redo,
  paintUndo,
  goals,
  liveGoals,
  doneGoals,
  finishGoal,
  reopenGoal,
  goalById,
  threadById,
  findThread,
  findStep,
  eventById,
  currentStep,
  lastDoneStep,
  newGoal,
  newThread,
  newStep,
  newSub,
  newEvent,
  logIt,
  touchThread,
  EPOCH,
  stampOf,
  STAMP_SKIP,
  recSig,
  eachRec,
  shadowReset,
  addGoal,
  deleteGoal,
  addEvent,
  removeEvent,
  skipOccurrence,
  occursOn,
  occurrenceOf,
  masterEvent,
  eventsOn,
  CAL,
  G_SCOPE,
  G_BACK_DAYS,
  G_FWD_DAYS,
  G_SYNCKEY,
  G_MAXPAGES,
  gmeta,
  gqueue,
  gCal,
  gOn,
  gClientId,
  gOriginOK,
  gCursor,
  gCursorSet,
  gLoadGIS,
  gRequestToken,
  gToken,
  gConnect,
  gDisconnect,
  gapi,
  gISO,
  gReadTime,
  gToRow,
  gFromRow,
  gWinFrom,
  gWinTo,
  inWindow,
  gDead,
  gForeign,
  gEnqueue,
  gPending,
  gFlush,
  gLease,
  gSync,
  gApply,
  gCancel,
  gDrop,
  gAdopt,
  gMerge,
  gStart,
  gStop,
  gChips,
  gAct,
  gPrefsHTML,
  gReadPrefs,
  BUDGET_COLOURS,
  budget,
  catColour,
  budgetState,
  fundableGoals,
  catProjection,
  logContribution,
  dayBudget,
  loadState,
  loadBar,
  paintBudget,
  commitBudget,
  budAct,
  viewBudget,
  budgetBarHTML,
  budgetSummaryHTML,
  TYPE,
  PIPELINE_STAGES,
  RULES,
  MONTHS,
  DOWS,
  parseWhen,
  parseClock,
  parseMoney,
  termsOf,
  overlap,
  learnType,
  learnedScore,
  classify,
  shortName,
  cadenceOf,
  buildGoalFrom,
  firstStepFor,
  subs,
  subProgress,
  sortSubs,
  addSub,
  moveItem,
  toggleSub,
  floatSub,
  carrySubs,
  completeStep,
  autoNextTitle,
  unblockThread,
  activeItems,
  itemsOn,
  unscheduledItems,
  overdueItems,
  daysQuiet,
  quietLimit,
  HUSH_AT,
  hushed,
  signals,
  sigKey,
  snoozeSignals,
  openGates,
  clearGate,
  lastDowKey,
  checkinDue,
  checkinAgenda,
  followThrough,
  streak,
  QUAD,
  ZOOMS,
  SIG_KIND,
  SIG_MAX,
  FIXABLE,
  captureView,
  restoreView,
  render,
  renderBody,
  renderSignals,
  sigResolverHTML,
  sigFixAct,
  itemCard,
  dayStripHTML,
  calPos,
  calMinAt,
  CAL_S,
  CAL_E,
  goalState,
  listHidden,
  quarterRange,
  doneCount,
  partialCount,
  bestQuadrant,
  CARDSUBS,
  CK_MAX,
  startCheckin,
  ckSaveProgress,
  ckNext,
  ckBack,
  subjHead,
  renderCheckin,
  suggestDay,
  suggestTime,
  ckAct,
  FOCUSABLE,
  openModal,
  closeModal,
  armConfirm,
  disarm,
  repaintArmed,
  armLabel,
  openConfirm,
  newInHTML,
  newInAct,
  doCapture,
  captureHint,
  wireView,
  wireDrag,
  toggleStep,
  openDefineNext,
  openEvent,
  openConvert,
  openGoal,
  refreshGoal,
  ordControls,
  schedRowHTML,
  subListHTML,
  goalEditorHTML,
  saveGoalFields,
  uiAct,
  geAct,
  openPrefs,
  BUILD,
  SW_URL,
  SW_WHY,
  swBlockedBecause,
  registerSW,
  standalone,
  iosWeb,
  installHint,
  renderInstallBar,
  doInstall,
  plyGoTo,
  installPrefsHTML,
  NOTIF_LEAD_MIN,
  NOTIF_HARD_H,
  NOTIF_WINDOW_MIN,
  NOTIF_TICK_MS,
  NOTIF_KEEP_DAYS,
  notifSupported,
  notifPerm,
  notifWanted,
  notifOn,
  notifTrackHard,
  notifSentList,
  notifAlreadySent,
  notifMark,
  notifPlan,
  notifShow,
  notifTick,
  notifStart,
  notifStop,
  notifEnable,
  notifDisable,
  notifPrefsHTML,
  TEMPLATES,
  TMPL_FIELDS,
  TMPL_GATE,
  fpMeta,
  LEARN_AFTER,
  tmplList,
  tmplGet,
  tmplBuiltin,
  tmplEdited,
  tmplSet,
  tmplReset,
  tmplHide,
  tmplShow,
  tmplAdd,
  matchTemplate,
  blankFootprint,
  normCost,
  normPrereq,
  normFootprint,
  fp,
  hasFootprint,
  footLead,
  footLag,
  footWidth,
  slotDur,
  costTotal,
  stepCost,
  ensureFootprint,
  applyTemplate,
  catByName,
  catNameOf,
  prereqDueKey,
  duePrereqs,
  prereqById,
  stepOfEvent,
  committedWeek,
  startActual,
  stopActual,
  clearActual,
  actualMins,
  timing,
  median,
  recordSample,
  tmplGates,
  clearTmplGate,
  queueTmplGate,
  proposeFromDuration,
  acceptTmplGate,
  declineTmplGate,
  MONEY_TARGET,
  stepById,
  carryFootprint,
  togglePrereq,
  applyFootprint,
  sigLabel,
  committedThisWeek,
  catSegStyle,
  footRowHTML,
  tmplPrefsHTML,
  parsePrereqSpec,
  parseCostSpec,
  ANCHOR_SOURCES,
  CHURN_SOURCES,
  CHURN_AT,
  churnAt,
  rescheduleHistory,
  rescheduleLifetime,
  blankReschedule,
  bumpReschedule,
  noteReschedule,
  rescheduleSummaryFromLog,
  recomputeAllReschedule,
  rescheduleLine,
  DRIFT_MIN_DAYS,
  DRIFT_SD_FACTOR,
  driftStats,
  rescheduleDrift,
  DRIFT_CADENCE_TYPES,
  GOAL_GATE_FIELDS,
  proposeFromDrift,
  avgDelta,
  driftPhrase,
  EASE_START,
  EASE_MIN,
  HINT_UNTIL, TIPS, TIP_DAYS, cardHTML, cardLabel, isCard, parseCard, pendingTips, retireTip,
  tilQueue, tipsOff, toggleHide, updateNote, wantsSyntaxHint, setTilEdit, setTilReveal,
  get TIL_REVEAL(){ return TIL_REVEAL; },
  get TIL_EDIT(){ return TIL_EDIT; },
  EASE_STEP,
  FIRST_INTERVAL,
  blankSrs,
  newNote,
  addNote,
  noteById,
  deleteNote,
  dueNotes,
  reviewNote,
  TIL_RE,
  isTilCapture,
  stripTil,
  seed,
  get DB(){ return DB; },
  set DB(v){ setDB(v); },
  get PASS(){ return PASS; },
  set PASS(_v){ /* owned by its module; no setter is exported */ },
  get MEMONLY(){ return MEMONLY; },
  set MEMONLY(_v){ /* owned by its module; no setter is exported */ },
  get EXTERNAL(){ return EXTERNAL; },
  set EXTERNAL(_v){ /* owned by its module; no setter is exported */ },
  get UNDO(){ return UNDO; },
  set UNDO(_v){ /* owned by its module; no setter is exported */ },
  get REDO(){ return REDO; },
  set REDO(_v){ /* owned by its module; no setter is exported */ },
  get PENDING(){ return PENDING; },
  set PENDING(_v){ /* owned by its module; no setter is exported */ },
  get GTOK(){ return GTOK; },
  set GTOK(_v){ /* owned by its module; no setter is exported */ },
  get GSTATE(){ return GSTATE; },
  set GSTATE(_v){ /* owned by its module; no setter is exported */ },
  get GERR(){ return GERR; },
  set GERR(v){ setGErr(v); },
  get GIS(){ return GIS; },
  set GIS(_v){ /* owned by its module; no setter is exported */ },
  get GTIMER(){ return GTIMER; },
  set GTIMER(_v){ /* owned by its module; no setter is exported */ },
  get GDONE(){ return GDONE; },
  set GDONE(_v){ /* owned by its module; no setter is exported */ },
  get CK(){ return CK; },
  set CK(v){ setCK(v); },
  get CKROW(){ return CKROW; },
  set CKROW(_v){ /* owned by its module; no setter is exported */ },
  get SIGOPEN(){ return SIGOPEN; },
  set SIGOPEN(v){ setSigOpen(v); },
  get SIGALL(){ return SIGALL; },
  set SIGALL(v){ setSigAll(v); },
  get SIGFIX(){ return SIGFIX; },
  set SIGFIX(v){ setSigFix(v); },
  get ARMED(){ return ARMED; },
  set ARMED(_v){ /* owned by its module; no setter is exported */ },
  get GEROW(){ return GEROW; },
  set GEROW(v){ setGerow(v); },
  get RETURN_FOCUS(){ return RETURN_FOCUS; },
  set RETURN_FOCUS(_v){ /* owned by its module; no setter is exported */ },
  get swallowClick(){ return swallowClick; },
  set swallowClick(_v){ /* owned by its module; no setter is exported */ },
  get lastZoomIdx(){ return lastZoomIdx; },
  set lastZoomIdx(_v){ /* owned by its module; no setter is exported */ },
  get SWREG(){ return SWREG; },
  set SWREG(v){ setSWREG(v); },
  get SWSTATE(){ return SWSTATE; },
  set SWSTATE(v){ setSWSTATE(v); },
  get INSTALL_EVT(){ return INSTALL_EVT; },
  set INSTALL_EVT(v){ setInstallEvt(v); },
  get NOTIF_TIMER(){ return NOTIF_TIMER; },
  set NOTIF_TIMER(_v){ /* owned by its module; no setter is exported */ },
  get SHADOW(){ return SHADOW; },
  set SHADOW(_v){ /* owned by its module; no setter is exported */ },
};

export default API;
